### ISSUE TITLE
About fid calculation formula

### ISSUE THREAD

**Issue by YaoshengFu** [bioinf-jku/TTUR#12]
you use the following formula to calculate fid:

d^2 = ||mu_1 - mu_2||^2 + Tr(C_1 + C_2 - 2*sqrt(C_1*C_2)).

The code uses dot product to calculate C_1*C_2, but the original formula seems to be based on matrix multiply. Could you clarify on this?

**Comment by mhex** [comment]
Hi, the dot product between two arrays/matrices in numpy is a matrix multiplication.

**Comment by YaoshengFu** [comment]
Oh you're right, I though it was element-wise multiply. Thanks!
