### ISSUE TITLE
[Not issue] Confusion in computing FID with pre-computed statistics.

### ISSUE THREAD

**Issue by PrateekMunjal** [bioinf-jku/TTUR#13]
I am using celebA datase where for training a GAN i preprocess the images to 64x64.
Further there are two methods mentioned to compute fid score which are : 
1. Method M1 -- run "fid.py <path_to_generated_samples> <path_to_original_images>"
2. Method M2 -- run "fid.py <path_to_generated_samples> <path_to_statistics file>"

Now as my generated samples are of 64x64 while statistics file available for celebA dataset [here](https://github.com/bioinf-jku/TTUR) is corresponding to original image size. Therefore I suspect that using M2 method will give me a wrong FID score.

Also to use M1 method, I thought of a solution to sample 10k images from celebA & store them by preprocessing the images to 64x64. Now I will have original samples (10k in numbers) which have same size as generated one i.e 64x64. 

Now my confusion is what do people do in practice i.e in papers when they report FID scores which method do they use M1 or M2 ?

**Comment by HRamses** [comment]
Hi!

Sorry for the late reply! The statistics are calculated on 64x64 images. In the utils.py file of the DCGAN implementation there are the functions: transform, center_crop and get_image. We used those for training and also for calculating the statistics. I.e. you should be fine with M2.
 
Btw: Thanks for the message! We didn't really make that clear.
