### ISSUE TITLE
Large System memory requirements when running FID

### ISSUE THREAD

**Issue by Pyrestone** [bioinf-jku/TTUR#14]
Hi, when using your script to compute the FID between two folders of 10k images (as is recommended) the system memory requirement of the script is gigantic.

I have looked into the script and seen that you load all of the images into RAM before starting to evaluate the statistics. Is there a way to handle this in batched form or even create a running version of the statistics?

That way it might take a little longer to compute, but would definitely relax the memory requirements by a large amount, which in will speed up the script by reducing swap space needed.

Thanks in advanced.

P.S: If you say this can be done, but don't have the time to do it, I can try implementing it myself and issue a pull request, but I'd like to know from you wether that would affect the correctness of the algorithm.

**Comment by Pyrestone** [comment]
I made a PR to resolve this issue. See #15

**Comment by untom** [comment]
Thanks for bringing this up, and kudos for taking the time to implementing it and sharing your solution :)
