### ISSUE TITLE
Question regarding FID Score

### ISSUE THREAD

**Issue by nobodykid** [bioinf-jku/TTUR#16]
Hello, I'm interested in using your code to evaluate several GAN models that I used as of now. Although, I have few question regarding your implementation of FID score

1. Recently I've been digging on implementation of FID, and found that Google released an evaluation paper using your method ([code](https://github.com/google/compare_gan)). However, they used Inception V3 while you still used Inception V1 here. Which one should I use?
2. From your code, I found that building the pretrained model using our data also need `batch_size` parameter. How does this affect the calculation? And which size is better for a given set of data?

**Comment by mhex** [comment]
Hi, thanks for using our code.

1. Can you give us a direct link where in the Google code they used Inception V3?

2. The parameter batch_size, as described in the code, splits the image data array in junks to propagate through the inception net. The calculation is not affected as the code collects the batched results (inception net activations) into one final array, one row for one image, to calculate the statistics.

**Comment by untom** [comment]
Hi!
The compare_gan code uses Inception V1, as they use the code from this TF module (which clearly uses V1): https://github.com/tensorflow/tensorflow/blob/r1.10/tensorflow/contrib/gan/python/eval/python/classifier_metrics_impl.py#L70
