### ISSUE TITLE
warnings module need be import in python3

### ISSUE THREAD

**Issue by HuMingqi** [bioinf-jku/TTUR#17]
https://github.com/bioinf-jku/TTUR/blob/dc4e5b5d02e1dd59a53b1d466a046402a5f69891/fid.py#L140-L142
The warnings module need be import explicitly. I got a error that the name is not defined by Python3.6, although it is usually not happened because the branch is often skipped.

**Comment by mhex** [comment]
We changed it, thanks for pointing this out!
