### ISSUE TITLE
Between np.trace(whole term) and sum of np.trace(each term)

### ISSUE THREAD

**Issue by nobodykid** [bioinf-jku/TTUR#18]
Hi, I found that you implemented the final FID calculation result in this line
```
return diff.dot(diff) + np.trace(sigma1) + np.trace(sigma2) - 2 * tr_covmean
```
But according to your formula, the trace are applied _after_ both sigmas and `covmean` being calculated, so it should be in
```
return diff.dot(diff) + np.trace(sigma1 + sigma2 - 2 * covmean)
```
I have experimented using both, and it seems that the calculation are both similar (until 13 numbers behind decimal point). Any explanation on reason of using the former?

**Comment by untom** [comment]
Hi! The two expressions are mathematically equivalent due to the rules of the trace operator, and the running time / memory consumption of the expression is negligible compared  to the calculation of the activations, so it doesn't really matter which one we use.
