### ISSUE TITLE
FID score in Table I 

### ISSUE THREAD

**Issue by ZhangDan0916** [bioinf-jku/TTUR#19]
Hi, 

In Table 1, the two FID scores for CelebA are completely identical to that of SVHN. From my own experiments, they are quite different. I would like to cross-check with you if this is an editing typo. Thanks.

**Comment by ZhangDan0916** [comment]
Hey, thanks for your prompt reply. One further question: for WGAN-GP Cifar10, which model did you use for Table 1? In the folder WGAN-GP, I only see the language model and gan_64x64. Did you use https://github.com/igul222/improved_wgan_training/blob/master/gan_cifar.py? with or without layer normalization, then? Thanks.

**Comment by mhex** [comment]
For all image datasets the gan_64x64 model was used.

**Comment by ZhangDan0916** [comment]
From my understanding, all discriminators in gan_64x64 except the fully connected one support image_size=64, because the reshape for the input to the last linear layer assumes the spatial dim of feature maps is 4. With cifar10, it would be 2. Therefore, I am a bit confused about the model for WGAN-GP Cifar10 in Table 1.  Thanks/Dan

**Comment by mhex** [comment]
You're right, just change the variable DIM in the script to 32 and it also works for Cifar10 32x32 images.
