### ISSUE TITLE
ValueError: setting an array element with a sequence.  

### ISSUE THREAD

**Issue by Prashant-mahajan** [bioinf-jku/TTUR#23]
Hi, 

I'm trying to get FID score on two dataset of Images (one real world data and other is GAN generated). 
Sizes: Real - 15780, Synthetic - 16000

Whenever I'm executing `python fid.py ` or  `python precalc_stats_example.py` I'm getting above mentioned error. I've attached the SS below: 

![Screenshot from 2019-07-18 15-31-18](https://user-images.githubusercontent.com/15001388/61486588-cac7c880-a971-11e9-8399-aa3c72a08b7a.png)

Any inputs would be appreciated!

**Comment by mhex** [comment]
What is the shape of your images object? It should be numpy array with shape and content (num_images, width, height, 3)

**Comment by Prashant-mahajan** [comment]
That fixed it, thanks!

**Comment by wissal54** [comment]
hi mhex, how to fixe the shape of images object, please?
