### ISSUE TITLE
Inception score for cifar10

### ISSUE THREAD

**Issue by Sumching** [bioinf-jku/TTUR#27]
Hi,

I changed dim to 32 and ran gan_64x64.py for cifar10 dataset, but I got 'IS_mean: 7.0972', 'IS_std: 0.0815',  FID: 32.4961. What's the problem?

**Comment by mhex** [comment]
Hi, we didn't calculate the IS in in gan_64x64.py so we can't comment on that. For the FID result, what TF version do you use? Have you trained the model at least for 150k iterations?

**Comment by Sumching** [comment]
I trained the model for 100k iterations, because of the default setting.  I noticed WGAN-GP posted the results of (IS 7.42 FID 29.3) using standard cnn(no resblocks) structure  and is FID 24.8 in your paper obtained by training resblock-based model?  And I will try to train the model for 150k iters. Thank you very much.
