### ISSUE TITLE
cannot find create_incpetion_graph()

### ISSUE THREAD

**Issue by BassyKuo** [bioinf-jku/TTUR#3]
It seems that there is no any `create_incpetion_graph()` definition in `fid.py`.
Also, the error message from fid_example.py runs as: 
```python
AttributeError: module 'fid' has no attribute 'create_incpetion_graph'
```
Have you met the same problem?

**Comment by BassyKuo** [comment]
I find the problem. `create_incpetion_graph` should be modified to `create_inception_graph` in [here](https://github.com/bioinf-jku/TTUR/blob/master/fid.py#L200) and [here](https://github.com/bioinf-jku/TTUR/blob/master/fid_example.py#L25).

**Comment by untom** [comment]
Thanks for spotting this and notifying us. Fixed in https://github.com/bioinf-jku/TTUR/commit/c36fc7438a2cf59d4b38d2ee98d4cc3985b55414 :)
