### ISSUE TITLE
I trained my GAN on cifar-10 (height,weight=32*32), and got FID=51. Should I resize the image to 64*64?

### ISSUE THREAD

**Issue by smallcube** [bioinf-jku/TTUR#30]
I trained my GAN on cifar-10 (height,weight=32*32), and got FID=51.  This score is much lower than the one reported in other paper.  Should I resize the image to 64*64?

**Comment by mhex** [comment]
This is not an issue related to the provided code. Please understand that we cannot discuss GAN models here, thank you.
